name: Build Docker image

on: [push]

env:
  POSTGRESQL_TAG: 12.10-alpine
  RETHINKDB_TAG: 2.4.0
  REDIS_TAG: 6.2.6
  PARABOL_DOCKER_REPOSITORY_DEV: parabol-dev
  PARABOL_DOCKER_REPOSITORY_PROD: parabol-prod


jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Start databases
        run: |
          docker run --name temp-postgres --network=host -e POSTGRES_PASSWORD=temppassword -e POSTGRES_USER=tempuser -e POSTGRES_DB=tempdb -d -p 5432:5432 postgres:${POSTGRESQL_TAG}
          docker run --name temp-rethinkdb --network=host -d -p 28015:28015 -p 29015:29015 -p 8080:8080 rethinkdb:${RETHINKDB_TAG}
          docker run --name temp-redis --network=host -d -p 6379:6379 redis:${REDIS_TAG}
          docker ps

      - name: Build the Docker image
        run: |
          echo ${PARABOL_DOCKER_REPOSITORY_DEV]:${github.sha}
          if [ ${github.ref_type} = "tag" ]; then
            echo ${PARABOL_DOCKER_REPOSITORY_PROD]:${github.ref_name}
          else
            echo ${PARABOL_DOCKER_REPOSITORY_DEV]:${github.ref_name}
          fi

      - name: Push the Docker images
        run: |
          echo "Authenticate to the Docker repositories"
          echo ${PARABOL_DOCKER_REPOSITORY_DEV]:${github.sha}
          if [ ${github.ref_type} = "tag" ]; then
            echo ${PARABOL_DOCKER_REPOSITORY_PROD]:${github.ref_name}
          else
            echo ${PARABOL_DOCKER_REPOSITORY_DEV]:${github.ref_name}
          fi
