on: [push]

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: release
      - run: |
          echo ${{ steps.release.outputs.release_created }}
          echo ${{ steps.release.outputs.upload_url }}
          echo ${{ steps.release.outputs.html_url }}
          echo ${{ steps.release.outputs.tag_name }}
          echo ${{ steps.release.outputs.major }}
          echo ${{ steps.release.outputs.minor }}
          echo ${{ steps.release.outputs.patch }}
          echo ${{ steps.release.outputs.sha }}
          echo ${{ steps.release.outputs.pr }}
          echo ${{ steps.release.outputs.prs }}
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Tagging the release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} || true
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
