on:
  push:
    branches:
      - release
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          command: manifest
          default-branch: release
      - name: Print tag if it was a release
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          echo ${{ steps.release-please.outputs.tag_name }}
